pipeline {
    agent none
    stages {
        stage('Maven Build') {
            agent { docker { image 'maven:3.8.1-adoptopenjdk-11' } }
            steps {
                sh 'ls -R'
                dir('backend') {
                    echo "--- Step 1: Downloading Dependencies & Compiling ---"
                    // mvn install puts the jar in your local .m2 repo
                    sh 'mvn clean install -DskipTests' 
                    
                    echo "--- Step 2: Packaging the Application ---"
                    // mvn package creates the JAR file in the 'target' folder
                    sh 'mvn package -DskipTests'
                }
            }
        }
        stage('NPM Build') {
            agent { docker { image 'node:16-alpine' } }
            steps {
                dir('frontend') {
                    echo "--- Step 1: Installing node_modules ---"
                    // This creates the 'node_modules' folder
                    sh 'npm install'
                    
                    echo "--- Step 2: Running Build Script ---"
                    // This executes the 'build' script defined in package.json
                    sh 'npm run build'
                }
            }
        }
    }
}
