pipeline {
    agent none
    stages {
        stage('Maven Build') {
            agent { 
                docker { 
                    image 'maven:3.8.1-adoptopenjdk-11' 
                    args '-u root:root'
                } 
            }
            steps {
                dir('helloworld/backend') {
                    echo "--- Step 1: Running Unit Tests ---"
                    // 'mvn test' scans src/test/java for any @Test annotations
                    sh 'mvn test' 

                    echo "--- Step 2: Packaging the Application ---"
                    // Now we remove -DskipTests because we want our tests to run during packaging too
                    sh 'mvn clean package' 
                }
            }
        }
        stage('NPM Build') {
            agent { 
                docker { 
                    image 'node:16-alpine' 
                    args '-u root:root'
                } 
            }
            steps {
                dir('helloworld/frontend') {
                    echo "--- Step 1: Installing node_modules ---"
                    // This creates the 'node_modules' folder
                    sh 'npm install'
                    
                    echo "--- Step 2: Running Build Script ---"
                    // This executes the 'build' script defined in package.json
                    sh 'npm run build'
                }
            }
        }
    }
}
